### PR TITLE
Responding to review feedback

### PR DESCRIPTION
**Pull request by mppf**
- [x] use -1.15 in all binary package names
- [x] adjust source package name as well
- [x] pull out qthreads stuff
- [x] change name from chapel-minimal
- [x] documented dependencies in table in README.source

Reviewed by @ben-albrecht - thanks!

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Looks good to me - let's wait for a response before merging.

**Comment by awallace-cray** [comment]
Which Chapel release will the debian package be- 1.15, from release branch? 1.16, from master-> new release branch, later?  A different pathway?  - thanks

**Comment by mppf** [comment]
@awallace-cray - we're using the 1.15 release tarball and then applying some Debian-specific patches. The Debian-specific patches include some things added to master recently, like `make install`.

**Comment by mppf** [comment]
@ben-albrecht - awaiting your review.
```
Generating lintian logs

lintian -I --show-overrides chapel-1.15_1.15.0-1.dsc

lintian -I --show-overrides chapel-1.15_1.15.0-1_amd64.changes
I: chapel-compiler-1.15: spelling-error-in-binary usr/bin/chpl dont don't

lintian -I --show-overrides chapel-1.15_1.15.0-1_amd64.deb

lintian -I --show-overrides chapel-common-1.15_1.15.0-1_all.deb

lintian -I --show-overrides chapel-compiler-1.15_1.15.0-1_amd64.deb
I: chapel-compiler-1.15: spelling-error-in-binary usr/bin/chpl dont don't

lintian -I --show-overrides chapel-compiler-1.15-dbgsym_1.15.0-1_amd64.deb
I: chapel-compiler-1.15-dbgsym: cannot-check-whether-usr-share-doc-symlink-points-to-foreign-package

lintian -I --show-overrides chapel-doc-1.15_1.15.0-1_all.deb

lintian -I --show-overrides chapel-runtime-1.15_1.15.0-1_amd64.deb
```

**Review by ben-albrecht — APPROVED** [review]
AFAIK, this is good to go

**Pull request merged**
